backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: static/media
public_folder: /media
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { label: 'Hidden', name: 'hidden', widget: 'boolean', default: false }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Canonical URL', name: 'canonical_url', widget: 'string',  required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    - name: 'markdown'
      label: 'Markdown'
      folder: 'src/markdown'
      create: true
      fields:
        - {
            label: 'Template Key',
            name: 'templateKey',
            widget: 'hidden',
            default: 'md-page',
          }
        - { label: 'Title', name: 'title', widget: 'string', required: false }
        - { label: 'Body', name: 'body', widget: 'markdown' }
